# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: LARP System Ideas
email: mat.gritt@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A place for me to put my larp concepts and have it versioned.
baseurl: "/larp" # the subpath of your site, e.g. /blog
url: "http://8wgremlin.github.io" # the base hostname & protocol for your site
twitter_username: @mat.gritt
github_username:  8wgremlin

# Build settings
markdown: kramdown
